### ISSUE TITLE
Information on how to get SDL2 working on OSX

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/rust-empty#175]
If you don't have `brew` installed, see https://github.com/PistonDevelopers/rust-empty/issues/177

This solution is relevant if you get an long error message when running `cargo build` ending in:

`ld: library not found for -lSDL2`
### Lacking permission to link SDL2

On some computers, the brew command fails to create the symlinks to the libraries it installs. This means the Rust compiler can not find them. To get permission to do this, use the `chown` command as following:

```
brew install sdl2
sudo chown root:wheel /usr/local/bin/brew
brew unlink sdl2 && brew link sdl2
```

### Missing path in LIBRARY_PATH environment variable

The Homebrew package manager symlinks library to the directory `/usr/local/lib`. To use these libraries with Rust, you need to add it to the `LIBRARY_PATH` environment variable. The command `echo $LIBRARY_PATH` will tell you if `/usr/local/lib` is added. If it is missing, add the following to the `~/.bash_profile` configuration file:

`export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"`

This will add the directory to the environment variable each time you start up a new Terminal window.

#### M1 Hardware

This solution was suggested by https://github.com/PistonDevelopers/rust-empty/issues/175#issuecomment-927172098

`export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib`

**Comment by rofrol** [comment]
On ubuntu 14.10:

    apt-get install libsdl2-dev

**Comment by adambadawy** [comment]
```
brew install sdl2
```
worked fine for me. I didn't take any other actions. Consider editing the info. here.

**Comment by tylerseymour** [comment]
For anyone arriving here recently, I'm just confirming that this is still an issue on MacOS Catalina as of August 2020, and that the provided solution by @bvssvni (Thank you!) still works. Only caveat is you'll need to add the $LIBRARY_PATH to your .zshrc, assuming you've migrated to it.

**Comment by nwilson314** [comment]
Spent a long time debugging the "ld: library not found for -lSDL2" issue on an M1 Mac with Big Sur. What ended up solving it for me was actually installing SDL2 via macports instead of homebrew. I have no idea why that matters (perhaps someone more knowledgeable than I can say) but I figured I'd post in case someone else runs into the same issue.

**Comment by kbolino** [comment]
Running `brew` as root is no longer supported, at least on recent versions of macOS on M1 hardware:

```console
% uname -r
20.6.0
% uname -m
arm64
% brew --version
Homebrew 3.2.13
Homebrew/homebrew-core (git revision ecf3c35ee41; last commit 2021-09-23)
% sudo brew link sdl2
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

However, `brew link sdl2` gives a hint for how to work around this:

```console
% brew link sdl2
Warning: Already linked: /opt/homebrew/Cellar/sdl2/2.0.16
To relink, run:
  brew unlink sdl2 && brew link sdl2
```

The link is now in /opt/homebrew/lib instead of /usr/local/lib. So the following solves the problem:

```console
% export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib"
```

**Comment by TomLisankie** [comment]
@kbolino Thank you!!

**Comment by EriKWDev** [comment]
In the interest of the public, given that this is still the first page that comes up for me when I google this issue, it would be great if there could be an edit made to the description above to include the new updated information by @kbolino 

@bvssvni

**Comment by bvssvni** [comment]
@EriKWDev Updated!
