### ISSUE TITLE
Cannot compile code on rust 1.29.1 and cargo 1.29.0

### ISSUE THREAD

**Issue by praveer-k** [PistonDevelopers/rust-empty#192]
cargo build
 Downloading piston3d-cam v0.3.0
 Downloading quaternion v0.3.0
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/praveerkumar/.cargo/registry/src/github.com-1ecc6299db9ec823/stb_truetype-0.2.5/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature``

**Comment by bvssvni** [comment]
This project has been deprecated.
