### ISSUE TITLE
Rustup installer no longer exists at previous web address, 

### ISSUE THREAD

**Issue by wsb1994** [PistonDevelopers/rust-empty#193]
The location of rustup.sh has moved.
Run the following command to install from the new location:
    curl https://sh.rustup.rs -sSf | sh

make nightly-install no longer works.

**Comment by bvssvni** [comment]
This project has been deprecated. There is a notice in the README.md, but I figured out it is not visible enough, so I added a notice in the project title.

**Comment by wsb1994** [comment]
no problem!
