### ISSUE TITLE
Information about git commands for contributing to other repositories

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/rust-empty#31]
1. Fork the repository by clicking the 'Fork' button on Github. This will copy the repository to your own Github account.
2. Clone your repository to local hard drive. This is the same as when creating a new repository on Github and starting to work on it locally.
3. Add 'upstream' remote with the command:

```
git remote add upstream <url>
```

The upstream remote should point to the original repository which you like to contribute to. After you do local commits you can pull from upstream with the command

```
git pull --rebase upstream master
```

This will update your master with commits from upstream and then apply your commits on top of them. Now you can push to your Github fork and then send a pull request.

```
git reset --soft upstream/master
```

This will merge your commits and open them for editing so you can write a new commit message.
## Squashing commits

If you need to squash the last 2 commits, you write:

`git reset --hard HEAD~2`
`git merge --squash HEAD@{1}`

Then you can write a new commit message.
If you get a conflict when trying to merge, you can use:

`git push --force origin master`

**Comment by RDeckers** [comment]
Question: Should collaborators accept their own pull requests, or should this be left up to the maintainers of each individual repo?

**Comment by bvssvni** [comment]
@RDeckers Self merge is encouraged, assuming you know what you are doing, see https://github.com/PistonDevelopers/piston/issues/674
